autograde-q1:
	podman run -v .:/code --rm -ti python:3.8 \
        bash -c "cd /code && python autograder.py -q q1 --no-graphics"

autograde-q2:
	podman run -v .:/code --rm -ti python:3.8 \
        bash -c "cd /code && python autograder.py -q q2 --no-graphics"

autograde-q3:
	podman run -v .:/code --rm -ti python:3.8 \
        bash -c "cd /code && python autograder.py -q q3 --no-graphics"

autograde-q4:
	podman run -v .:/code --rm -ti python:3.8 \
        bash -c "cd /code && python autograder.py -q q4 --no-graphics"

autograde-q5:
	podman run -v .:/code --rm -ti python:3.8 \
        bash -c "cd /code && python autograder.py -q q5 --no-graphics"

autograde-q6:
	podman run -v .:/code --rm -ti python:3.8 \
        bash -c "cd /code && python autograder.py -q q6 --no-graphics"

autograde-q7:
	podman run -v .:/code --rm -ti python:3.8 \
        bash -c "cd /code && python autograder.py -q q7 --no-graphics"

autograde-q8:
	podman run -v .:/code --rm -ti python:3.8 \
        bash -c "cd /code && python autograder.py -q q8 --no-graphics"

autograde-q9:
	podman run -v .:/code --rm -ti python:3.8 \
        bash -c "cd /code && python autograder.py -q q9 --no-graphics"

autograde-q10:
	podman run -v .:/code --rm -ti python:3.8 \
        bash -c "cd /code && python autograder.py -q q10 --no-graphics"
