@startuml

state "Кредит" as S1 {
    state "Договор кредита\nсоздан" as S1.1
    state "Кредит на\nрассмотрении" as S1.2
    state "Кредит закреплён\nза клиентом" as S1.3
    state "Кредит уничтожен" as S1.4
    
    [*]  ->       S1.1 : Клиент хочет\nоформить кредит
    S1.1 ->       S1.2 : Передача договора\nотделу Кредитования
    S1.2 --->     S1.3 : Кредит\nодобрен
    S1.2 -->      S1.4 : Кредит\nотклонён
    S1.3 ->       S1.3 : Выплата\nкредита
    S1.3 --->     S1.4 : Кредит\nвыплачен
    S1.4 -------> S1.1 : Оформить новый\nкредит
    S1.4 -right-> [*]
}

state "Депозит" as S2 {
    state "Договор депозита\nсоздан" as S2.1
    state "Депозит на\nрассмотрении" as S2.2
    state "Депозит закреплён\nза клиентом" as S2.3
    state "Депозит уничтожен" as S2.4
    
    [*]  ->       S2.1 : Клиент хочет\nоформить депозит
    S2.1 ->       S2.2 : Передача договора\nотделу открыия Депозитов
    S2.2 --->     S2.3 : Депозит\nодобрен
    S2.2 -->      S2.4 : Депозит\nотклонён
    S2.3 --->     S2.4 : Клиент желает\nзакрыть депозит
    S2.4 -------> S2.1 : Оформить новый депозит
    S2.4 -right-> [*]
}

state "Карта" as S3 {
    state "Подготовлен договор\nформления карты" as S3.1
    state "Карта существует" as S3.2
    state "Карта просрочена" as S3.3

    [*] --> S3.1 : Клиент хочет\nпривязать карту\nк счёту
    S3.1 --> S3.2 : Оформление\nодобрено
    S3.2 -down-> S3.3 : Окончание срока\nвалидности
    S3.3 -up-> S3.2 : Перевыпуск\nкарты
    S3.1 --> [*] : В оформлении\nотказано
    S3.3 -right-> [*]
}


@enduml
