@startuml

|Клиент|
|Отдел Кредитов и Депозитов|



|Клиент|
start

|Клиент|
:Заполнить договор;
:Отправить запрос;

|Отдел Кредитов и Депозитов|
:Оценить клиента;
if () then (Клиенту можно выдать кредит)
    :Выдать кредит;
    |Клиент|
    :Выплачивать кредит;
    |Отдел Кредитов и Депозитов|
    :Сохранить в кредитную историю;
else (Клиенту нет доверия)
    |Отдел Кредитов и Депозитов|
    :Отказать в выдаче;
    |Клиент|
endif
stop

@enduml
